[phases.setup]
nixPkgs = ["python310", "gcc", "libffi", "openssl", "zlib", "libjpeg", "libpng"]

[phases.build]
cmds = ["pip install -r requirements.txt", "python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn booking_saas.wsgi:application --bind 0.0.0.0:$PORT"
